import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";

// Load the Inter font with optional configurations
const inter = Inter({
  subsets: ["latin"], // Specify the subset(s) you want to load
  variable: "--font-inter", // Define a CSS variable for the font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply the Inter font to the body */}
      <body className={`${inter.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}